#!/usr/bin/env bash
# Regenerate the Rust miner's golden test vectors from the canonical DERO Go
# reference (deroref/, a verbatim copy of github.com/deroproject/derohe/astrobwt
# plus the side-effect instrumentation hooks in deroref/astrobwtv3/harness_hooks.go).
#
# The Rust suites in astrobwt/tests/{prologue,full,pow16,sais}_vectors.rs load
# these; they are NOT committed-as-generated by default, so a fresh clone runs
# this once. The v114 golden fixture (astrobwt/tests/fixtures/) is separate and
# IS committed.
#
#   ./run.sh            # regenerate all four vector files
#   ./run.sh sais       # just one suite
#
# Requires Go (1.21+). Aborts if the reference fails the shipped known-answer
# vectors, so a mis-copied reference can never emit vectors.
set -euo pipefail
cd "$(dirname "$0")"
OUT="../vectors"
mkdir -p "$OUT"

go run . selfcheck   # KAT gate: pow("a") == 54e2324d…, or abort

gen() { echo "  vectors/$1.json"; go run . "$1" > "$OUT/$1.json"; }

case "${1:-all}" in
  all)      gen astrobwt; gen pow16; gen sais ;;
  astrobwt) gen astrobwt ;;
  pow16)    gen pow16 ;;
  sais)     gen sais ;;
  *) echo "usage: run.sh [all|astrobwt|pow16|sais]" >&2; exit 2 ;;
esac
echo "done."
