//! `--bench` mode — port of the benchmark block (cmd/dero-miner/miner.go:181-203)
//! and `random_execution` (miner.go:378-394): for t in 1..=threads, run t
//! threads each computing 1000 AstroBWTv3 hashes over a thread-local 255-byte
//! random buffer, printing the Go-format `%20s`-per-column table.
//!
//! Durations print through [`format_go_duration`], a faithful port of Go's
//! `time.Duration.String()` (verified against Go vectors in
//! vectors/minerwork.json) so the table reads identically.

use std::time::{Duration, Instant};

use dero_astrobwt::{astrobwtv3_with_scratch, AstroBwtScratch};

/// Go `time.Duration.String()`: sub-second values use ns/µs/ms with up to
/// 0/3/6 fractional digits (trailing zeros dropped); >= 1s uses `[Nh][Nm]N.Ns`
/// with up to 9 fractional second digits.
pub fn format_go_duration(d: Duration) -> String {
    let u = d.as_nanos();
    if u == 0 {
        return "0s".to_string();
    }
    if u < 1_000_000_000 {
        let (prec, unit) = if u < 1_000 {
            (0u32, "ns")
        } else if u < 1_000_000 {
            (3u32, "µs")
        } else {
            (6u32, "ms")
        };
        return format!("{}{}", fmt_with_frac(u, prec), unit);
    }
    let frac = frac_digits(u % 1_000_000_000, 9);
    let total_secs = u / 1_000_000_000;
    let s = total_secs % 60;
    let m = (total_secs / 60) % 60;
    let h = total_secs / 3600;
    let mut out = String::new();
    if h > 0 {
        out.push_str(&format!("{h}h"));
    }
    if h > 0 || m > 0 {
        out.push_str(&format!("{m}m"));
    }
    out.push_str(&format!("{s}{frac}s"));
    out
}

/// `u` scaled by 10^prec → "int[.frac]" with trailing zeros trimmed.
fn fmt_with_frac(u: u128, prec: u32) -> String {
    let pow = 10u128.pow(prec);
    let int = u / pow;
    let frac = frac_digits(u % pow, prec as usize);
    format!("{int}{frac}")
}

/// Fractional part as ".ddd" (width `prec`, trailing zeros trimmed), or "".
fn frac_digits(frac: u128, prec: usize) -> String {
    if prec == 0 || frac == 0 {
        return String::new();
    }
    let s = format!("{frac:0prec$}");
    let s = s.trim_end_matches('0');
    format!(".{s}")
}

/// Go `%20s`: right-pad to 20 BYTES (Rust's `{:>20}` pads by chars — differs
/// for the 2-byte `µ` in µs durations).
fn pad20(s: &str) -> String {
    let pad = 20usize.saturating_sub(s.len());
    format!("{}{}", " ".repeat(pad), s)
}

/// One Go-format table row: `fmt.Printf("%20s %20s %20s %20s %20s \n", ...)`.
fn bench_row(c0: &str, c1: &str, c2: &str, c3: &str, c4: &str) -> String {
    format!(
        "{} {} {} {} {} ",
        pad20(c0),
        pad20(c1),
        pad20(c2),
        pad20(c3),
        pad20(c4)
    )
}

/// miner.go:181-203. Note Go's quirks, replicated: the per-PoW time is the
/// integer division `duration / (threads*iterations)` (a Duration), and the
/// hashrate is computed in f32 and printed with `%.1f`.
pub fn run_bench(threads: usize) {
    println!(
        "{}",
        bench_row(
            "Threads",
            "Total Time",
            "Total Iterations",
            "Time/PoW ",
            "Hash Rate/Sec"
        )
    );
    let iterations = 1000u32;
    for bench in 1..=threads {
        let now = Instant::now();
        let mut handles = Vec::new();
        for _ in 0..bench {
            handles.push(std::thread::spawn(move || {
                // Go random_execution: a 255-byte random buffer per thread
                let mut workbuf = [0u8; 255];
                rand::Rng::fill(&mut rand::thread_rng(), &mut workbuf[..]);
                let mut scratch = AstroBwtScratch::new();
                for _ in 0..iterations {
                    std::hint::black_box(astrobwtv3_with_scratch(&workbuf, &mut scratch));
                }
            }));
        }
        for h in handles {
            h.join().expect("bench thread panicked");
        }
        let duration = now.elapsed();
        let total_iterations = bench as u32 * iterations;
        let per_pow = duration / total_iterations;
        // Go: float32(time.Second) / float32(duration/total)
        let rate = 1_000_000_000f32 / (per_pow.as_nanos() as f32);
        println!(
            "{}",
            bench_row(
                &bench.to_string(),
                &format_go_duration(duration),
                &total_iterations.to_string(),
                &format_go_duration(per_pow),
                &format!("{rate:.1}"),
            )
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Durations must format exactly like Go's time.Duration.String()
    /// (vectors generated by go-harness/minerwork via the real Go stdlib).
    #[test]
    fn go_duration_strings_match_vectors() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/vectors/minerwork.json");
        let v: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
        let cases = v["durations"].as_array().unwrap();
        assert!(cases.len() >= 10);
        for c in cases {
            let ns = c["ns"].as_u64().unwrap();
            let want = c["str"].as_str().unwrap();
            assert_eq!(format_go_duration(Duration::from_nanos(ns)), want, "{ns}ns");
        }
    }

    #[test]
    fn bench_row_format_matches_go_columns() {
        // %20s-style right alignment with a trailing space, exactly the Go
        // fmt.Printf("%20s %20s %20s %20s %20s \n", ...) layout.
        let row = bench_row(
            "1",
            &format_go_duration(Duration::from_nanos(1_531_672_800)),
            "1000",
            &format_go_duration(Duration::from_nanos(1_531_672)),
            &format!("{:.1}", 1_000_000_000f32 / 1_531_672f32),
        );
        assert_eq!(row, "                   1           1.5316728s                 1000           1.531672ms                652.9 ");

        // Go %20s pads by BYTES: "153.167µs" is 9 chars but 10 bytes -> 10 spaces.
        let micro = format_go_duration(Duration::from_nanos(153_167));
        assert_eq!(micro, "153.167µs");
        assert_eq!(pad20(&micro), "          153.167µs");
        assert_eq!(pad20(&micro).len(), 20, "padded to 20 bytes like Go");
    }
}
